# Generated by Django 3.0.2 on 2020-03-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0002_haber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('haber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haber.Haber')),
            ],
        ),
    ]
