# Generated by Django 3.0.2 on 2020-03-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0003_auto_20200328_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
