# Generated by Django 3.0.2 on 2020-04-05 18:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0004_auto_20200331_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
