# Generated by Django 3.0.2 on 2020-04-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0005_auto_20200405_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
