# Generated by Django 3.0.2 on 2020-04-25 21:19
import uuid
from django.db import migrations, models

from haber.models import Category


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0009_comment_user'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in Category.objects.all():
            row.slug = uuid.uuid4()
            row.save()

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
            preserve_default=True,
        ),
        migrations.RunPython(gen_uuid),

        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),

    ]
