# Generated by Django 3.0.2 on 2020-04-25 21:50
import uuid
from django.db import migrations, models

from haber.models import Haber


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0011_auto_20200426_0042'),
    ]
    def gen_uuid(apps, schema_editor):
        for row in Haber.objects.all():
            row.slug = uuid.uuid4()
            row.save()

    operations = [
        migrations.AddField(
            model_name='haber',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
            preserve_default=True,
        ),
        migrations.RunPython(gen_uuid),

        migrations.AlterField(
            model_name='haber',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
