# Generated by Django 3.0.2 on 2020-04-25 21:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0012_auto_20200426_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
